= Requirements

== Portability

The Build Tool should basically run everywhere where Java runs.

== Resource processors

These processors are intended for pre-assembling usage.

=== Charpad converter

Converts Charpad source file into the following outcomes:

* charset file,
* block definition,
* map definition.

Any of the outcome is optional.
Any of the outcome can be either and assembly file or binary file.
Each of the outcome can result in more than one file (i.e. big map can be divided into few smaller maps using coordinates).

=== Spritepad converter

=== GoatTracker converter

=== PNG converter

== Generic processors

These processors can be used at any stage of building.

=== Cruncher/packer

== Postprocessors

These processors are intended for post-assembling usage.

=== 1541 disk maker

Produces one or more 1541 disk images with:

* given directory structure,
* converted binary files,
* assembled binary files,
* source binary files.

=== TAP maker

Produces a TAP file with blocks originated from:

* converted binary files,
* assembled binary files,
* source binary files.
