= Overview

== Retro assembler project model

The source model of any retro assembler (MOS 6502 based) project is very simplified.
There is no interim form of compilation process and there is no linker.
The only means to reuse shared code is to use import directive therefore for the project it is sufficient to know all entry point files and assembly them one by one into executables (i.e. PRG files).
All internal dependencies are specified within source files.
All external dependencies must be handled externally (via retro assembler build tool).

image:img/domain-asm-project-model.svg[]

There are other kind of files kept in the project:

* data files of Charpad or similar software for developing tiled-based backgrounds,
* data files of Spritepad or similar software for developing sprites,
* source files of GoatTracker for SID music sources,
* plain images in any format to be displayed.

All these files should be kept in source form and then convert via processors to embeddable form (i.e. binary).
It should be possible to compress binary form if needed, i.e. via Exomizer.

image:img/domain-processors.svg[]

