/*
MIT License

Copyright (c) 2018-2025 c64lib: The Ultimate Commodore 64 Library
Copyright (c) 2018-2025 Maciej Małecki

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
package com.github.c64lib.rbt.flows.domain

/** Represents a flow - a chain of related tasks that can be executed as a unit */
data class Flow(
    val name: String,
    val steps: List<FlowStep> = emptyList(),
    val dependsOn: List<String> = emptyList(), // Names of other flows this flow depends on
    val produces: List<FlowArtifact> = emptyList(), // Artifacts produced by this flow
    val consumes: List<FlowArtifact> = emptyList(), // Artifacts consumed by this flow
    val description: String = ""
) {
  /** Adds a step to this flow */
  fun addStep(step: FlowStep): Flow = copy(steps = steps + step)

  /** Adds a dependency on another flow */
  fun dependsOn(flowName: String): Flow = copy(dependsOn = dependsOn + flowName)

  /** Adds an artifact that this flow produces */
  fun produces(artifact: FlowArtifact): Flow = copy(produces = produces + artifact)

  /** Adds an artifact that this flow consumes */
  fun consumes(artifact: FlowArtifact): Flow = copy(consumes = consumes + artifact)
}

/** Represents a single step within a flow */
data class FlowStep(
    val name: String,
    val taskType: String, // e.g., "kickass", "charpad", "spritepad"
    val inputs: List<String> = emptyList(),
    val outputs: List<String> = emptyList(),
    val configuration: Map<String, Any> = emptyMap()
)

/** Represents an artifact (file or resource) that flows between different flows */
data class FlowArtifact(
    val name: String,
    val path: String,
    val type: ArtifactType,
    val description: String = "",
    val isSourceFile: Boolean = false // Indicates if this artifact comes directly from source files
) {
  companion object {
    /** Creates a source file artifact that doesn't need a producer */
    fun sourceFile(
        name: String,
        path: String,
        type: ArtifactType,
        description: String = ""
    ): FlowArtifact = FlowArtifact(name, path, type, description, isSourceFile = true)

    /** Creates a produced artifact that should be generated by another flow */
    fun produced(
        name: String,
        path: String,
        type: ArtifactType,
        description: String = ""
    ): FlowArtifact = FlowArtifact(name, path, type, description, isSourceFile = false)
  }
}

/** Types of artifacts that can be produced/consumed by flows */
enum class ArtifactType {
  SOURCE_FILE, // .asm source files
  COMPILED_BINARY, // .prg compiled binaries
  CHARSET_DATA, // Character set data from charpad
  SPRITE_DATA, // Sprite data from spritepad
  MUSIC_DATA, // Music data from goattracker
  IMAGE_DATA, // Processed image data
  DEPENDENCY_FILE, // Dependency metadata
  TEST_RESULT // Test execution results
}
